/camera_node:
  ros__parameters:
    camera_info_url: package://rm_vision_bringup/config/camera_info.yaml
    exposure_time: 2600
    gain: 8.0

/serial_driver:
  ros__parameters:
    timestamp_offset: 0.0068
    device_name: /dev/ttyACM0
    baud_rate: 115200
    flow_control: none
    parity: none
    stop_bits: "1"

/armor_detector:
  ros__parameters:
    debug: true

    detect_color: 0
    binary_thres: 80

    light.min_ratio: 0.09
    armor.min_light_ratio: 0.7

    classifier_threshold: 0.8
    ignore_classes: ["negative"]

/armor_tracker:
  ros__parameters:
    target_frame: odom
    max_armor_distance: 10.0

    ekf:
      sigma2_q_xyz: 0.05  #0.05
      sigma2_q_yaw: 10.0
      sigma2_q_r: 80.0

      r_xyz_factor: 0.0002
      r_yaw: 0.005

    tracker:
      max_match_distance: 0.15
      max_match_yaw_diff: 0.85

      tracking_thres: 3
      lost_time_thres: 3.0